reserved-for-future-use: ENC[AES256_GCM,data:Nt1WrmWK3oMAwKQ=,iv:2zSssSnM0/tPFWOUbJVrpNUmHRHenlYsu1c44wLtyAo=,tag:fWesImnUmB2g/1+OT11skg==,type:str]
sops:
    age:
        - recipient: age1kmcfw420lmcsw67s4vjdws5xmlncmqavs9k3xp79jw8jccv53yjsjhp79w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyY1BNaUx2bnZFMktINE42
            YXh4SUhGejZPSG1LQ2p2OUFYb3ZyNGlLa2xJCjhYVEhsQ2cyeVdMRFI0ZnJzVVE2
            a0syS01ZaTNGdEZhNDh1MmFudWZCZTAKLS0tIDc1Uld2em5vbVJIdzlNbEFxWGhm
            TTdscVRtMWRHeUdzUnhLRTBrQ2JpY0EKgTGHhmm9qbhwBVoDUP68YvHj7I42leMY
            Rs0t8gg7zDwu1F+edXx72nuzYtBXjbvJS//gpgPgqerqkbIXZ00qTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T18:56:39Z"
    mac: ENC[AES256_GCM,data:v28c0LT9CatKQujppHefoS60jzYKPqeyYv5eJJbFZ/hzHDPxyvnDWEE4sOGwWjjEECcxNaVgZWYkq7wX+EWEtP4Uic7ZSBaNgu40yKSE2HgaNy4rl+U177EZsnrbo/pOB9nR8UD8bEQ3ka8a3cmUHQ8GWn3TVoH4LmCisUr3w7g=,iv:wvt/BwKmOWylhXTKUtFyGsn15k6dCCj2acK1pkTrEEo=,tag:PeaHDIkpaS7SW5TCF35ZUQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|immutable)$
    version: 3.10.2
