reserved-for-future-use: ENC[AES256_GCM,data:k0XgMNgRswKll86gECfyPJIm3Q==,iv:shFnBeV85o/wHpX/xJUyGOBEf+V5rmZ9zlC6PxRpX28=,tag:kE5Qk5G6Er+4bEo951u1mA==,type:str]
openrouter-api-key: ENC[AES256_GCM,data:ReIhC317GuhhTlkhdDy3rKqc5PF0HjBaTqAGZeGfwgzVU/FGZ1wzLGifUh5kvvnuzMBylb6rn3CvXKnriwy00vjL/gcSi80u6Q==,iv:5T+jbFbrQBlZ1Te3AByjvLzeRbOX0Ww4KNA7+ckKfiM=,tag:HGKxPumDLYCR+Xs/a2hWuQ==,type:str]
opencode-zen-api-key: ENC[AES256_GCM,data:/xzcBzZug+YLF2WpjRjVq2yIM0R+EKzACkFzyeIp0KrXLLmPgsiJ0BwATzRfMdVW5m5OHG04oOHmVJP7+EKuHnTT5g==,iv:H5KLCqiknfxB/9ABPXzEvBpqebTVPBBfWIrqMw/BEI0=,tag:n1fO2o7tbtyIUJtUT64jZQ==,type:str]
sops:
  age:
    - recipient: age1kmcfw420lmcsw67s4vjdws5xmlncmqavs9k3xp79jw8jccv53yjsjhp79w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyY1BNaUx2bnZFMktINE42
        YXh4SUhGejZPSG1LQ2p2OUFYb3ZyNGlLa2xJCjhYVEhsQ2cyeVdMRFI0ZnJzVVE2
        a0syS01ZaTNGdEZhNDh1MmFudWZCZTAKLS0tIDc1Uld2em5vbVJIdzlNbEFxWGhm
        TTdscVRtMWRHeUdzUnhLRTBrQ2JpY0EKgTGHhmm9qbhwBVoDUP68YvHj7I42leMY
        Rs0t8gg7zDwu1F+edXx72nuzYtBXjbvJS//gpgPgqerqkbIXZ00qTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T06:26:38Z"
  mac: ENC[AES256_GCM,data:T6d/4bzIyYJ0ASA0Qv9uJ2Wi4Kf6RGQniIToiFotTifHe2pxuPeQ2VzpQECjxuI0eGl66zcnNvRGbdEqS7pmg/5ZkRQv9RfxEDTVkHJthRi2J0aBXF8mzDpQNyNhE3cNBHLf+qSoa902UaZHA9fxnktIRDtXu3EC9i2e6vhksWg=,iv:9K2PddZNG0Rg2FDLrgZDHpEqfPaANa/81xF3zUlDEy4=,tag:Iymg59ZHxcDYb72JkAN9ZQ==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type|immutable)$
  version: 3.12.2
