stores:
  yaml:
    indent: 2
creation_rules:
  - path_regex: .*\.enc\.(yaml|yml|json|env)$
    unencrypted_regex: ^(apiVersion|metadata|kind|type|immutable)$
    age: age1kmcfw420lmcsw67s4vjdws5xmlncmqavs9k3xp79jw8jccv53yjsjhp79w
