version: "3"

tasks:
  switch:
    aliases:
      - s
    vars:
      HOST: "{{ .Env.hostname }}"
    cmds:
      - |
        {{ if eq OS "darwin" }}
          nix run nix-darwin -- switch --flake .#{{ .HOST }} {{.CLI_ARGS}}
        {{ else }}
          sudo nixos-rebuild switch --flake .#{{ .HOST }} {{.CLI_ARGS}}
        {{end}}

  gc:
    cmds:
      - sudo nix-collect-garbage --delete-older-than 7d
      - sudo nix store optimise

  list-project-files:
    cmds:
      - bun run {{.ROOT_DIR}}/scripts/list-project-files.ts {{.CLI_ARGS}}

  create-big-file:
    cmds:
      - bun run {{.ROOT_DIR}}/scripts/create-big-file.ts {{.CLI_ARGS}}
