version: "3"

tasks:
  switch:
    aliases:
      - s
    vars:
      HOST: "{{ .Env.hostname }}"
    cmds:
      - |
        {{ if eq OS "darwin" }}
          nix run nix-darwin -- switch --flake .#{{ .HOST }} {{.CLI_ARGS}}
        {{ else }}
          sudo nixos-rebuild switch --flake .#{{ .HOST }} {{.CLI_ARGS}}
        {{end}}
    silent: true
