version: "3"

tasks:
  switch:
    aliases:
      - s
    vars:
      HOST: "{{ .Env.hostname }}"
    cmds:
      - |
        {{ if eq OS "darwin" }}
          nix run nix-darwin -- switch --flake .#{{ .HOST }} {{.CLI_ARGS}}
        {{ else }}
          sudo nixos-rebuild switch --flake .#{{ .HOST }} {{.CLI_ARGS}}
        {{end}}

  gc:
    cmds:
      - sudo nix-collect-garbage --delete-older-than 7d
      - sudo nix store optimise

  run-*:
    aliases:
      - r
    vars:
      SCRIPT_NAME: "{{index .MATCH 0}}"
    cmds:
      - bun run {{.ROOT_DIR}}/scripts/{{.SCRIPT_NAME}}.ts {{.CLI_ARGS}}
