{pkgs, ...}: {
  programs.nix-ld.libraries = with pkgs; [
    alsa-lib.out
    at-spi2-atk.out
    at-spi2-core.out
    atk
    cairo.out
    glamoroustoolkit.out
    cups.lib
    curl
    dbus.lib
    expat
    fontconfig
    freetype
    fuse3
    gdk-pixbuf
    glib.out
    glib.debug
    gtk3
    icu
    libappindicator-gtk3
    libgcc.lib
    libdrm
    libGL
    libglvnd
    libnotify
    libpulseaudio
    libunwind
    libusb1
    libuuid
    libxkbcommon.out
    libxml2
    mesa.out
    nspr.out
    nss_latest.out
    openssl
    pango.out
    pipewire
    stdenv.cc.cc
    systemd
    vulkan-loader
    xorg.libX11.out
    xorg.libxcb.out
    xorg.libXcomposite.out
    xorg.libXcursor.out
    xorg.libXdamage.out
    xorg.libXext.out
    xorg.libXfixes.out
    xorg.libXi.out
    xorg.libxkbfile.out
    xorg.libXrandr.out
    xorg.libXrender.out
    xorg.libXScrnSaver.out
    xorg.libxshmfence.out
    xorg.libXtst.out
    xorg_sys_opengl.out
    zlib.out
  ];
}
